### ISSUE TITLE
F1的计算

### ISSUE THREAD

**Issue by bellytina** [Buted/SSJDN#1]
您好，请问在evalute时，是否需要忽略掉文本中没有触发词的情况？
也就是 若golden_tag 为’O O O O O ...‘ 或者 pred_tag为’O O O O O ...‘ 时 不对其计数
我在代码里没找到的相应的实现

**Comment by Buted** [comment]
评估时忽略文本中正确预测的非触发词（golden='O'且pred='O'）。但要是golden != 'O'或pred != 'O'，就会被计入错误样本。详见：
https://github.com/Buted/SSJDN/blob/547e8bf3bfe495691b53b1c8e568a38b3ec63f3a/enet/testing.py#L51
