### ISSUE TITLE
About KBP2015 Issue

### ISSUE THREAD

**Issue by Deadmau555** [Buted/SSJDN#2]
I have recently studied your work on EMNLP2021 and feel very inspired, are you convenient to provide the dataset of KBP2015? I have been looking for it through many ways, but have not been able to find it, and need it urgently！！！

**Comment by Buted** [comment]
hello, u can download it from https://tac.nist.gov/2015/KBP/data.html. Due to the commercial agreement, I can't offer the dataset directly. 
Hope this will help you!

**Comment by xxllp** [comment]
这个能用在中文数据集上面吗
