### ISSUE TITLE
ACE复现结果

### ISSUE THREAD

**Issue by kk19990709** [Buted/SSJDN#3]
您好，我根据https://github.com/nlpcl-lab/ace2005-preprocessing 的数据进行划分，分数只有72。使用您的划分标准，可以复现出合理的结果。
请问为什么会存在这种差异？您数据集划分的依据是什么？
感谢！

**Comment by Buted** [comment]
我们当时先根据https://github.com/nlpcl-lab/ace2005-preprocessing 的数据进行划分，发现很多已有方法都无法达到预期效果。于是我们意识到可能是数据的具体划分问题，实验中不同划分方式最终的结果的确会有差异。但在随机几次以后仍然很难复现那些方法，就采用了最后一次随机划分作为论文实验的划分。

**Comment by kk19990709** [comment]
感谢解答！我们也发现事件检测的很多论文都无法达到预期效果。
很喜欢你们的工作！
