### ISSUE TITLE
关于数据集划分的问题

### ISSUE THREAD

**Issue by alderpaw** [Buted/SSJDN#4]
您好，我在其他issue中看到您这篇工作对于ACE数据集使用的是自己的划分方式。但是您在对比其他sota模型的时候，似乎是直接引用的他们报告的结果，这个结果可能不是在此划分下跑出来的，在对比上会不会存在一些问题呢？

**Comment by Buted** [comment]
good question! 
每个论文的划分方式应该都不一样，在我们的划分下，实现的结果与他们论文中差距太大，所以只能引用他们的结果进行对比。
